name: vipepeo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.0.2
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_form_builder: ^6.1.0+1
  flutter_image_compress: ^1.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  http: ^0.13.4
  image_picker: ^0.8.4+2
  location: ^4.3.0
  multiple_select: ^0.1.24
  awesome_select: ^5.0.3
  permission_handler: ^8.2.5
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
